# Conda Environment Configuration
# E-commerce Market Research & Customer Segmentation Analysis
# Author: Bryant M.
# Date: July 2025

name: online_retail_analysis

channels:
  - conda-forge
  - defaults
  - anaconda

dependencies:
  # Python version
  - python=3.9

  # Core Data Science Stack
  - pandas=2.0.3
  - numpy=1.24.3
  - scipy=1.11.1

  # Machine Learning & Statistics
  - scikit-learn=1.3.0
  - statsmodels=0.14.0
  - xgboost=1.7.6

  # Visualization Libraries
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0

  # Jupyter Environment
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - notebook=6.5.4
  - jupyterlab=4.0.2

  # File Processing
  - openpyxl=3.1.2
  - xlrd=2.0.1

  # Configuration & Templates
  - pyyaml=6.0.1
  - jinja2=3.1.2

  # Progress & Utilities
  - tqdm=4.65.0

  # Date/Time Processing
  - python-dateutil=2.8.2

  # Development Tools
  - pip=23.1.2

  # Optional: Performance & Profiling
  - memory_profiler=0.60.0
  - line_profiler=4.0.3

  # Pip-only dependencies
  - pip:
    # Web Framework for Dashboard
    - dash==2.11.1
    - dash-bootstrap-components==1.4.1
    
    # Report Generation
    - weasyprint==59.0
    
    # Additional utilities
    - colorama==0.4.6